// Scans apps/web/public/media/clips for encoded scroll-world clips and writes the manifest
// the scene config reads. Run after media/scripts/04-encode.sh.
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("../..", import.meta.url)));
const dir = resolve(root, "apps/web/public/media/clips");
const order = ["opening-track", "landing", "ascent", "garden", "trail", "chamber", "finale", "one-more-song"];
const files = existsSync(dir) ? new Set(readdirSync(dir)) : new Set();
const clips = {}, clipsMobile = {};
for (const id of order) {
  if (files.has(`${id}.mp4`)) clips[id] = `/media/clips/${id}.mp4`;
  if (files.has(`${id}-m.mp4`)) clipsMobile[id] = `/media/clips/${id}-m.mp4`;
}
const connectors = order.slice(0, -1).map((_, i) => (files.has(`conn${i + 1}.mp4`) ? `/media/clips/conn${i + 1}.mp4` : null));
const connectorsMobile = order.slice(0, -1).map((_, i) => (files.has(`conn${i + 1}-m.mp4`) ? `/media/clips/conn${i + 1}-m.mp4` : null));
// Phones scrub image sequences (media/scripts/05-frames-m.sh) instead of video.
const fdir = resolve(root, "apps/web/public/media/frames");
const fmeta = existsSync(resolve(fdir, "frames.json")) ? JSON.parse(readFileSync(resolve(fdir, "frames.json"), "utf8")) : { fps: 12, width: 540 };
const frameSet = (id) => {
  const d = resolve(fdir, id);
  if (!existsSync(d)) return null;
  const names = readdirSync(d).filter((f) => /^f\d+\.webp$/.test(f)).sort();
  // Frames keep their paths across re-renders and /media is browser-cached for a day, so the
  // engine appends ?v=<hash of names+sizes>; a re-render changes the hash and busts the cache.
  const v = createHash("sha1").update(names.map((f) => f + ":" + statSync(resolve(d, f)).size).join("|")).digest("hex").slice(0, 8);
  return names.length ? { base: `/media/frames/${id}/`, count: names.length, fps: fmeta.fps, v } : null;
};
const framesMobile = {};
for (const id of order) { const f = frameSet(id); if (f) framesMobile[id] = f; }
const connectorsFramesMobile = order.slice(0, -1).map((_, i) => frameSet(`conn${i + 1}`));
// Poster versions (same reason): scenes.ts appends ?v= to /media/scenes/<id>[-m].webp.
const sdir = resolve(root, "apps/web/public/media/scenes");
const posterV = {};
for (const id of order) {
  const parts = [`${id}.webp`, `${id}-m.webp`].map((f) => (existsSync(resolve(sdir, f)) ? f + ":" + statSync(resolve(sdir, f)).size : ""));
  posterV[id] = createHash("sha1").update(parts.join("|")).digest("hex").slice(0, 8);
}
const out = { note: "Generated by `npm run media:manifest` after the scroll-world pipeline encodes clips. Scenes without an entry render their poster only.", clips, clipsMobile, connectors, connectorsMobile, framesMobile, connectorsFramesMobile, posterV };
writeFileSync(resolve(root, "apps/web/src/config/media-manifest.json"), JSON.stringify(out, null, 2) + "\n");
console.log(out);
