// Scans apps/web/public/media/clips for encoded scroll-world clips and writes the manifest
// the scene config reads. Run after media/scripts/04-encode.sh.
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(new URL("../..", import.meta.url).pathname);
const dir = resolve(root, "apps/web/public/media/clips");
const order = ["opening-track", "landing", "ascent", "garden", "trail", "chamber", "finale"];
const files = existsSync(dir) ? new Set(readdirSync(dir)) : new Set();
const clips = {}, clipsMobile = {};
for (const id of order) {
  if (files.has(`${id}.mp4`)) clips[id] = `/media/clips/${id}.mp4`;
  if (files.has(`${id}-m.mp4`)) clipsMobile[id] = `/media/clips/${id}-m.mp4`;
}
const connectors = order.slice(0, -1).map((_, i) => (files.has(`conn${i + 1}.mp4`) ? `/media/clips/conn${i + 1}.mp4` : null));
const connectorsMobile = order.slice(0, -1).map((_, i) => (files.has(`conn${i + 1}-m.mp4`) ? `/media/clips/conn${i + 1}-m.mp4` : null));
const out = { note: "Generated by `npm run media:manifest` after the scroll-world pipeline encodes clips. Scenes without an entry render their poster only.", clips, clipsMobile, connectors, connectorsMobile };
writeFileSync(resolve(root, "apps/web/src/config/media-manifest.json"), JSON.stringify(out, null, 2) + "\n");
console.log(out);
