"""Temporary poster plates from the campus photographs (replaced later by clay renders).
Usage: python3 media/scripts/posters.py
"""
from pathlib import Path
from PIL import Image, ImageFilter, ImageEnhance

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "Assets"
OUT = ROOT / "apps/web/public/media/scenes"
OUT.mkdir(parents=True, exist_ok=True)

# scene -> (source file, landscape crop anchor y 0..1)
PLATES = {
    "landing": ("주차장_운동장_웰컴스팟용 블럭_1.jpg", 0.5),
    "ascent": ("The Ascent_Route1_1.jpg", 0.42),
    "garden": ("본관 앞 분수_4.jpg", 0.5),
    "trail": ("채플과 본관 연결부_잔듸광장_2.jpg", 0.5),
    "chamber": ("채플_1.jpg", 0.5),
    "finale": ("본관 앞 분수_2.jpg", 0.5),   # same fountain terrace as 04, different angle — jazz busking happens here
}

def cover(img, w, h, ay=0.5):
    sw, sh = img.size
    scale = max(w / sw, h / sh)
    img = img.resize((round(sw * scale), round(sh * scale)), Image.LANCZOS)
    x = (img.width - w) // 2
    y = round((img.height - h) * ay)
    return img.crop((x, y, x + w, y + h))

def autumn(img):
    """A gentle warm grade so the summer photos read closer to the event's palette."""
    img = ImageEnhance.Color(img).enhance(0.92)
    r, g, b = img.split()
    r = r.point(lambda v: min(255, int(v * 1.06 + 4)))
    b = b.point(lambda v: int(v * 0.9))
    return Image.merge("RGB", (r, g, b))

STILLS = ROOT / "media/work/stills"   # clay scene stills (Track 2) win over photo plates
import os
VIDEO_FRAMES = ROOT / "media/work" / os.environ.get("POSTER_SOURCE", "") / "first_{}.png" if os.environ.get("POSTER_SOURCE") else None
def source_for(scene):
    """POSTER_SOURCE=previz|final → the dive's actual first frame (so the poster equals frame 0 of the clip)."""
    if VIDEO_FRAMES is not None:
        f = ROOT / "media/work" / os.environ["POSTER_SOURCE"] / f"first_{scene}.png"
        if f.exists(): return f
    f = STILLS / f"still_{scene}.png"
    return f if f.exists() else None

for scene, (name, ay) in PLATES.items():
    still = source_for(scene)
    if still is not None:
        src = Image.open(still).convert("RGB")
        cover(src, 1920, 1080, 0.5).save(OUT / f"{scene}.webp", quality=84, method=6)
        cover(src, 1080, 1920, 0.5).save(OUT / f"{scene}-m.webp", quality=82, method=6)
        print("poster", scene, "from", still.relative_to(ROOT))
        continue
    src = Image.open(SRC / name).convert("RGB")
    autumn(cover(src, 1920, 1080, ay)).save(OUT / f"{scene}.webp", quality=82, method=6)
    autumn(cover(src, 1080, 1920, ay)).save(OUT / f"{scene}-m.webp", quality=80, method=6)
    print("poster", scene, "(photo plate)")

# opening track: clay still if present, else a stand-in built from the chapel lobby light
ot = source_for("opening-track")
if ot is not None:
    src = Image.open(ot).convert("RGB")
    cover(src, 1920, 1080).save(OUT / "opening-track.webp", quality=84, method=6)
    cover(src, 1080, 1920).save(OUT / "opening-track-m.webp", quality=82, method=6)
    print("poster opening-track from", ot.relative_to(ROOT))
else:
  # no photograph of the Changdong lounge yet — a warm, out-of-focus
  # stand-in built from the chapel lobby light so the scene has a coherent plate.
  lobby = Image.open(SRC / "채플_4_안쪽 로비_1.jpg").convert("RGB")
  warm = autumn(cover(lobby, 1920, 1080)).filter(ImageFilter.GaussianBlur(14))
  warm = ImageEnhance.Brightness(warm).enhance(0.8)
  warm.save(OUT / "opening-track.webp", quality=80, method=6)
  autumn(cover(lobby, 1080, 1920)).filter(ImageFilter.GaussianBlur(14)).save(OUT / "opening-track-m.webp", quality=78, method=6)
  print("poster opening-track (stand-in)")

# overture: the clay anchor if it exists, else the finale plate
# newest approved anchor first (v3a = corrected terrain/stair/chapel, 2026-09-04)
anchor = next((ROOT / "media/anchor" / n for n in ("anchor-v5b.png", "anchor-v5a.png", "anchor-v4-vivid.png", "anchor-v4-natural.png", "anchor-v3a.png", "anchor-a.png") if (ROOT / "media/anchor" / n).exists()), ROOT / "media/anchor/none.png")
ov = Image.open(anchor).convert("RGB") if anchor.exists() else Image.open(SRC / "채플과 본관 연결부_잔듸광장_2.jpg").convert("RGB")
stem = anchor.stem if anchor.exists() else "photo"
for old in OUT.glob("overture-*.webp"):
    old.unlink()
hero = OUT / f"overture-{stem}.webp"
cover(ov, 1920, 1080).save(hero, quality=84, method=6)
cover(ov, 1600, 840).save(ROOT / "apps/web/public/media/og.jpg", quality=86)
hero_ts = ROOT / "apps/web/src/config/hero.ts"
hero_ts.write_text(f'// Generated by media/scripts/posters.py — versioned so browser caches never show a stale hero.\nexport const heroImage = "/media/scenes/{hero.name}";\n')
print("overture + og", f"from {stem}")
