// Generated by media/scripts/posters.py — versioned so browser caches never show a stale hero.
export const heroImage = "/media/scenes/overture-anchor-v5b.webp";
// Portrait hero for phones (9:19.5), from media/anchor/<stem>-phone.jpg when it exists.
export const heroImageMobile: string | null = "/media/scenes/overture-anchor-v5b-m.webp";
